Repository publdaze/cs-study, pull requests merged in 2024-04, with the labels that each got.

#1 publdaze: [1회독] P1_Ch7-8 운영체제 면접 대비
  README.md
  publdaze/CS 핵심요약집 1회독/P1_운영체제.md
Labels: 운영체제, 1회독

#2 sososo0: [1회독] P1_Ch1 운영체제
  README.md
  sososo0/CS 핵심요약집 1회독/P1_운영체제.md
Labels: 운영체제, 1회독

#3 publdaze: [1회독] P1_Ch1 운영체제
  README.md
  publdaze/CS 핵심요약집 1회독/P1_운영체제.md
Labels: 운영체제, 1회독

#4 publdaze: [1회독] P1_Ch2 프로세스
  README.md
  publdaze/CS 핵심요약집 1회독/P1_운영체제.md
Labels: 운영체제, 1회독

#5 publdaze: [1회독] P1_Ch3 스케줄링
  README.md
  publdaze/CS 핵심요약집 1회독/P1_운영체제.md
Labels: 운영체제, 1회독

#6 publdaze: [1회독] P1_Ch4 메모리 관리 전략
  README.md
  publdaze/CS 핵심요약집 1회독/P1_운영체제.md
Labels: 운영체제, 1회독

#7 publdaze: [1주차 발표] P1_Process States
  README.md
  publdaze/발표자료/Process_States.pdf
Labels: 운영체제, 발표

#8 publdaze: [1회독] P1_Ch5 가상 메모리
  README.md
  publdaze/CS 핵심요약집 1회독/P1_운영체제.md
Labels: 운영체제, 1회독

#10 publdaze: [1회독] P2_Ch5-6 네트워크 면접 대비
  README.md
  publdaze/CS 핵심요약집 1회독/P2_네트워크.md
Labels: 컴퓨터 네트워크, 1회독
