Repository publdaze/cs-study, pull requests merged in 2024-05, with the labels that each got.

#11 publdaze: [2주차 발표] P1_OS 간단 정리 1
  README.md
  publdaze/발표자료/OS간단정리_1.pdf
Labels: 운영체제, 발표

#12 publdaze: [1회독] P2_Ch1 네트워크 계층
  README.md
  publdaze/CS 핵심요약집 1회독/P2_네트워크.md
Labels: 컴퓨터 네트워크, 1회독

#14 publdaze: [1회독] P2_Ch2 TCP와 UDP
  README.md
  publdaze/CS 핵심요약집 1회독/P2_네트워크.md
Labels: 컴퓨터 네트워크, 1회독

#15 publdaze: [3주차 발표] P1_OS 간단 정리 2
  README.md
  publdaze/발표자료/OS간단정리_2.pdf
Labels: 운영체제, 발표

#16 publdaze: [1회독] P2_Ch3 HTTP
  README.md
  publdaze/CS 핵심요약집 1회독/P2_네트워크.md
Labels: 컴퓨터 네트워크, 1회독

#17 publdaze: [1회독] P2_Ch4 REST
  README.md
  publdaze/CS 핵심요약집 1회독/P2_네트워크.md
Labels: 컴퓨터 네트워크, 1회독

#18 publdaze: [1회독] P4_Ch1 ~ Ch3 복잡도, 자료구조
  README.md
  publdaze/CS 핵심요약집 1회독/P4_자료구조.md
Labels: 자료구조, 1회독

#19 publdaze: [1회독] P4_Ch4-5 자료구조 면접 대비
  README.md
Labels: 자료구조, 1회독

#20 publdaze: [1회독] P5_Ch1 정렬 알고리즘
  README.md
  publdaze/CS 핵심요약집 1회독/P5_알고리즘.md
Labels: 알고리즘, 1회독

#22 docs: 체크리스트 반영
  README.md
Labels: 알고리즘, 1회독

#23 publdaze: [4주차 발표] P1_OS 간단 정리 3
  README.md
  publdaze/발표자료/OS간단정리_3.pdf
Labels: 운영체제, 발표

#24 publdaze: [4주차 면접] P1_OS 면접
  README.md
  publdaze/면접질문/운영체제.md
Labels: 운영체제, 모의 면접

#26 Pipisebastian
  README.md
  pipisebastian/발표자료/CPU_스케줄링.pdf
Labels: 운영체제, 발표
